#!/usr/local/bin/node

/*
    coon
        add <host-config-name> with <deploy-config-name>
            "wizard" or
            [--ssh-host <ssh-host>] [--ssh-user <ssh-user>] [--ssh-privatekey <ssh-path-to-private-key>] [--ssh-port <ssh-port>] [--branch <branch-name>] [--build-command <build command>] [--source <source>] [--target <target>]  

        add host <host-config-name>
            "wizard" or
            [--ssh-host <ssh-host>] [--ssh-user <ssh-user>] [--ssh-privatekey <ssh-path-to-private-key>] [--ssh-port <ssh-port>]

        add deploy <deploy-config-name>
            "wizard" or 
            [--branch <branch-name>] [--build-command <build command>] [--source <source>] [--target <target>]  

        show <configs | hosts | deploys>

        remove 
            all <configs | hosts | deploys>
            host <name>
            deploy <name>

        edit <deploy | host> <name>
            "wizard" or
            [--ssh-host <ssh-host>] [--ssh-user <ssh-user>] [--ssh-privatekey <ssh-path-to-private-key>] [--ssh-port <ssh-port>] [--branch <branch-name>] [--build-command <build command>] [--source <source>] [--target <target>]  


        deploy <deploy-name> to <host-name>
            [--ssh-host <ssh-host>] [--ssh-user <ssh-user>] [--ssh-privatekey <ssh-path-to-private-key>] [--ssh-port <ssh-port>] [--branch <branch-name>] [--build-command <build command>] [--source <source>] [--target <target>] 
        // delay-deploy <deploy-name> <host-name> [branch-name]
        
        build <deploy-name>

        bind <deploy-name> to <host-name>
            [--ssh-host <ssh-host>] [--ssh-user <ssh-user>] [--ssh-privatekey <ssh-path-to-private-key>] [--ssh-port <ssh-port>] [--branch <branch-name>] [--build-command <build command>] [--source <source>] [--target <target>] 

        unbind <deploy-name> [from <host-name>]

*/ 



